module.exports = {
  atom: 'atom',
  Brackets: 'brackets',
  code: 'code',
  'code-insiders': 'code-insiders',
  codium: 'codium',
  emacs: 'emacs',
  gedit: 'gedit',
  'goland.sh': 'goland',
  gvim: 'gvim',
  'idea.sh': 'idea',
  kate: 'kate',
  leafpad: 'leafpad',
  mousepad: 'mousepad',
  'phpstorm.sh': 'phpstorm',
  pluma: 'pluma',
  'pycharm.sh': 'pycharm',
  'rider.sh': 'rider',
  'rubymine.sh': 'rubymine',
  sublime_text: 'subl',
  vim: 'vim',
  vscodium: 'vscodium',
  'webstorm.sh': 'webstorm',
  xed: 'xed'
}
